version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=P@ssw0rd
    ports:
      - 8083:8083
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
      - ./99proxy:/etc/apt/apt.conf.d/99proxy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./99proxy:/etc/apt/apt.conf.d/99proxy
      - ./plugin/grafana-status-panel:/var/lib/grafana/plugins/grafana-status-panel
      - ./plugin/grafana-worldping-app:/var/lib/grafana/plugins/grafana-worldping-app
      - ./plugin/grafana-zabbix:/var/lib/grafana/plugins/grafana-zabbix
      - ./plugin/grafana-worldmap-panel:/var/lib/grafana/plugins/grafana-worldmap-panel
      - ./plugin/grafana-statusmap:/var/lib/grafana/plugins/grafana-statusmap
      - ./plugin/grafana-radar-panel:/var/lib/grafana/plugins/grafana-radar-panel
      - ./plugin/grafana-piechart-panel:/var/lib/grafana/plugins/grafana-piechart-panel
      - ./plugin/grafana-polystat-panel:/var/lib/grafana/plugins/grafana-polystat-panel
      - ./plugin/grafana-dot-status:/var/lib/grafana/plugins/grafana-dot-status
      - ./plugin/grafana-multistat-panel:/var/lib/grafana/plugins/grafana-multistat-panel
      - ./plugin/grafana-diagram:/var/lib/grafana/plugins/grafana-diagram
      - ./plugin/grafana-clock-panel:/var/lib/grafana/plugins/grafana-clock-panel

  telegraf:
    image: telegraf:latest
    container_name: vsphere-telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./99proxy:/etc/apt/apt.conf.d/99proxy
    labels:
      - "traefik.enable=false"
    networks:
      - monitoring


networks:
  monitoring:
    external: true
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
